### PR TITLE
Upgrade AppMesh specs

### PR DESCRIPTION
**Pull request by kayaman**
**Issue #** (if available): #81 

## License

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by nithu0115** [comment]
@kayaman, Thanks for this contribution and I apologize for the delay. 

I will quickly test it out and merge it.

**Comment by kayaman** [comment]
Thanks @nithu0115! I'll double check it on my side. It's been a few days already, I don't remember what was missing for me to leave the PR as WIP.

**Comment by kayaman** [comment]
@nithu0115 I tested. Everything looks good here. There are problemas on other parts, I'll open issues. But this PR can be merged. Thanks!

**Comment by nithu0115** [comment]
@kayaman, I have also tested this over weekend, LGTM!

Thanks

**Comment by kayaman** [comment]
@nithu0115 news?

**Pull request merged**
